[command]
info = "<gold>T-Nexus</gold> <white><arg:0></white> is running."

[command.reload]
success = "<green>Configuration reloaded. Debug: <arg:0></green>"
failed = "<red>Failed to reload the configuration.</red>"